"""跨方言 DDL 回归测试。

纯静态断言 ``Base.metadata`` / 各方言编译出的 DDL，无需真实数据库连接，
用于守护之前修复过的跨库兼容问题，防止回归：
- 整型主键自增（Oracle ORA-01400）
- 主键冗余索引（Oracle ORA-01408）
- MSSQL 可空列唯一索引重复 NULL
- Oracle/MSSQL 空串处理（OrEmptyStr/OrEmptyText 必须可空）
"""

import re

import pytest
from sqlalchemy.dialects import mysql, mssql, oracle, postgresql, sqlite
from sqlalchemy.schema import CreateIndex, CreateTable

from app import models
from app.models.types import OrEmptyStr, OrEmptyText

DIALECTS = {
    "sqlite": sqlite.dialect(),
    "mysql": mysql.dialect(),
    "postgresql": postgresql.dialect(),
    "mssql": mssql.dialect(),
    "oracle": oracle.dialect(),
}


def _column_ddl(ddl: str, col_name: str) -> str:
    """从 CreateTable DDL 中取出某列的定义行（含列名、类型、约束）。"""
    m = re.search(rf"(?m)^\s*{re.escape(col_name)}\s+.*$", ddl)
    return m.group(0).strip() if m else ""


@pytest.mark.parametrize("dialect_name", list(DIALECTS))
def test_integer_pk_auto_increment(dialect_name):
    """主键列必须为自增（identity），避免 Oracle ORA-01400。"""
    dialect = DIALECTS[dialect_name]
    for table in models.Base.metadata.tables.values():
        for col in table.columns:
            if not col.primary_key:
                continue
            # 元数据级：Integer 主键必须配置 Identity()
            assert col.identity is not None, (
                f"{table.name}.{col.name} 主键缺少 Identity()（方言 {dialect_name}）"
            )
            # DDL 级：编译结果需含对应方言的自增标记
            ddl = _column_ddl(
                str(CreateTable(table).compile(dialect=dialect)), col.name
            )
            if dialect_name in ("oracle", "postgresql"):
                assert "GENERATED BY DEFAULT AS IDENTITY" in ddl, ddl
            elif dialect_name == "mssql":
                assert "IDENTITY" in ddl, ddl
            elif dialect_name == "mysql":
                assert "AUTO_INCREMENT" in ddl, ddl
            elif dialect_name == "sqlite":
                # SQLite 用 INTEGER PRIMARY KEY（rowid 别名）自增
                assert "INTEGER" in ddl, ddl


def test_pk_no_redundant_index():
    """主键列不应再建冗余索引（避免 Oracle ORA-01408）。"""
    for table in models.Base.metadata.tables.values():
        for col in table.columns:
            if col.primary_key:
                assert not getattr(col, "index", False), (
                    f"{table.name}.{col.name} 主键仍带 index=True"
                )
        redundant = f"ix_{table.name}_id"
        assert redundant not in {idx.name for idx in table.indexes}, (
            f"{table.name} 存在冗余主键索引 {redundant}"
        )


@pytest.mark.parametrize("dialect_name", list(DIALECTS))
def test_mssql_nullable_unique_index_filtered(dialect_name):
    """可空列上的唯一索引：MSSQL 须用过滤索引，其他方言为普通唯一索引。"""
    dialect = DIALECTS[dialect_name]
    for table in models.Base.metadata.tables.values():
        for idx in table.indexes:
            if not idx.unique:
                continue
            nullable_cols = [c for c in idx.columns if c.nullable]
            if not nullable_cols:
                continue
            compiled = str(CreateIndex(idx).compile(dialect=dialect))
            if dialect_name == "mssql":
                assert "WHERE" in compiled and "IS NOT NULL" in compiled, compiled
                assert "UNIQUE" in compiled, compiled
            else:
                assert "WHERE" not in compiled, compiled


def test_empty_string_columns_nullable():
    """OrEmptyStr/OrEmptyText 列必须可空，避免 Oracle 空串 ORA-01400。"""
    for table in models.Base.metadata.tables.values():
        for col in table.columns:
            if isinstance(col.type, (OrEmptyStr, OrEmptyText)):
                assert col.nullable, (
                    f"{table.name}.{col.name} 使用 OrEmpty* 类型却不可空"
                )


@pytest.mark.parametrize("dialect_name", list(DIALECTS))
def test_all_schema_compiles_across_dialects(dialect_name):
    """所有表的建表与索引在每种方言下都能编译（schema 可移植性 smoke）。"""
    dialect = DIALECTS[dialect_name]
    for table in models.Base.metadata.tables.values():
        CreateTable(table).compile(dialect=dialect)
        for idx in table.indexes:
            CreateIndex(idx).compile(dialect=dialect)
